'use client';
import Link from 'next/link';
import { GraduationCap, Plus, Users, CalendarDays, BookOpen, Gauge, AlertTriangle, ArrowRight, RefreshCw } from 'lucide-react';
import { useGetMeQuery,useGetTrainingOverviewQuery,useGetTrainingProgramsQuery } from '@/app/redux/api/TrainingApiSlice';
import { useTrainingScope } from './layout';
const rows=value=>value?.content||[];

export default function TrainingDashboardPage(){
 const me=useGetMeQuery(); const organizationId=me.data?.organizations?.[0]?.id; const {projectId}=useTrainingScope();
 const overview=useGetTrainingOverviewQuery({organizationId},{skip:!organizationId}); const programs=useGetTrainingProgramsQuery({organizationId,page:0,size:100},{skip:!organizationId});
 const allPrograms=rows(programs.data); const visible=projectId?allPrograms.filter(item=>String(item.projectId)===String(projectId)):allPrograms;
 const sessionCount=visible.reduce((sum,item)=>sum+(item.sessionCount||0),0); const active=visible.filter(item=>['ACTIVE','PLANNED'].includes(item.status)).length;
 const loading=me.isLoading||overview.isLoading||programs.isLoading; const error=me.error||overview.error||programs.error;
 const metrics=[{label:'Training programs',value:visible.length,detail:`${active} active or planned`,icon:BookOpen,href:'/dashboard/training/programs'},{label:'Participants',value:overview.data?.participants??0,detail:'Reusable organization roster',icon:Users,href:'/dashboard/training/participants'},{label:'Sessions',value:sessionCount,detail:'Inside selected programs',icon:CalendarDays,href:'/dashboard/training/sessions'},{label:'Readiness',value:'Live',detail:'Derived from evidence, never entered manually',icon:Gauge,href:'/dashboard/training/readiness'}];
 if(loading)return <div className="space-y-5 animate-pulse"><div className="h-44 rounded-2xl bg-navy/8"/><div className="grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-32 rounded-xl bg-navy/5"/>)}</div></div>;
 if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center"><AlertTriangle className="mx-auto text-red-500"/><h1 className="mt-3 text-xl font-bold text-navy">Training data could not be loaded</h1><p className="mt-2 text-sm text-navy/50">The server returned {error?.data?.message||'an unavailable response'}.</p><button onClick={()=>window.location.reload()} className="mt-5 inline-flex items-center gap-2 rounded-md bg-navy px-4 py-2 font-bold text-white"><RefreshCw size={15}/>Retry</button></div>;
 return <div className="space-y-6"><section className="relative overflow-hidden rounded-2xl bg-navy p-6 text-white sm:p-8"><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-white/50"><GraduationCap size={16}/>Operational training</div><h1 className="mt-4 text-3xl font-bold sm:text-4xl">Training command center</h1><p className="mt-3 max-w-2xl text-white/60">Plan delivery, assign people, capture attendance and assessments in context, resolve blockers, and explain readiness.</p></div><Link href="/dashboard/training/programs" className="inline-flex items-center justify-center gap-2 rounded-lg bg-white px-5 py-3 font-bold text-navy"><Plus size={16}/>Create program</Link></div></section>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,detail,icon:Icon,href})=><Link key={label} href={href} className="rounded-xl border border-navy/8 bg-white p-5 shadow-sm transition-shadow hover:shadow-md"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-lg bg-navy/5"><Icon size={18}/></span><ArrowRight size={15} className="text-navy/20"/></div><p className="mt-5 text-3xl font-bold text-navy">{value}</p><p className="mt-1 text-sm font-bold text-navy/60">{label}</p><p className="mt-2 text-xs text-navy/35">{detail}</p></Link>)}</div>
 <section className="overflow-hidden rounded-xl border border-navy/8 bg-white"><div className="border-b border-navy/6 p-5"><h2 className="font-bold text-navy">Programs in scope</h2><p className="mt-1 text-xs text-navy/40">Open a program to manage modules, roles, sessions, attendance, assessments, and blockers.</p></div>{visible.length?<div className="divide-y divide-navy/5">{visible.slice(0,8).map(item=><Link key={item.id} href={`/dashboard/training/programs/${item.id}`} className="flex items-center justify-between p-5 hover:bg-navy/[.02]"><div><p className="font-bold text-navy">{item.title}</p><p className="mt-1 text-xs text-navy/40">{item.memberCount} members · {item.sessionCount} sessions</p></div><span className="rounded-full bg-navy/5 px-3 py-1 text-xs font-bold text-navy">{item.status}</span></Link>)}</div>:<div className="p-12 text-center"><BookOpen className="mx-auto text-navy/15"/><p className="mt-3 font-bold text-navy">No programs in this scope</p><p className="mt-1 text-sm text-navy/40">Create one or select a different project.</p></div>}</section></div>;
}
